ansible==2.4.1.0
asn1crypto==0.23.0
bcrypt==3.1.4
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
click==6.7
cryptography==2.1.3
enum34==1.1.6
Flask==0.12.2
idna==2.6
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
netaddr==0.7.19
paramiko==2.4.0
pkginfo==1.4.1
pyasn1==0.4.2
pycparser==2.18
PyNaCl==1.2.0
PyYAML==3.12
requests==2.18.4
requests-toolbelt==0.8.0
six==1.11.0
tqdm==4.19.4
twine==1.9.1
urllib3==1.22
Werkzeug==0.12.2
