ansible==2.4.1.0
asn1crypto==0.23.0
bcrypt==3.1.4
cbkutils==1.0
cffi==1.11.2
click==6.7
cryptography==2.1.3
enum34==1.1.6
Flask==0.12.2
idna==2.6
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.10
jsonpickle==0.9.5
MarkupSafe==1.0
netaddr==0.7.19
paramiko==2.4.0
pyasn1==0.4.2
pycparser==2.18
Pygments==2.2.0
PyNaCl==1.2.0
PyYAML==3.12
six==1.11.0
Werkzeug==0.12.2
